NoMasAccidentes/Controllers/AuthController.cs
using NoMasAccidentesNegocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.Mvc;

namespace NoMasAccidentes.Controllers
{
    public class AuthController : Controller
    {
       public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(Usuario usuario,string ReturnUrl)
        {
            if (IsValid(usuario))
            {
                FormsAuthentication.SetAuthCookie(usuario.Email, false);
                if (ReturnUrl != null)
                {
                    return Redirect(ReturnUrl);
                }
                return RedirectToAction("Index", "Home");
            }
            TempData["mensaje"] = "Credenciales Incorrecta";
            return View(usuario);
        }
        private bool IsValid(Usuario usuario)
        {


            return usuario.Autenticar();

         //if (usuario.Email == "admin@admin.cl" && usuario.Password == "admin")

         // {
         //     return true;
         // }
         //  return false;
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

NoMasAccidentes/Controllers/ContratoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NoMasAccidentesNegocio;


namespace NoMasAccidentes.Controllers
{   
    [Authorize]
    public class ContratoController : Controller
    {
        // GET: Contrato
        public ActionResult Index()
        {
            ViewBag.Contratos = new Contrato().ReadAll();
            return View();
        }

        // GET: Contrato/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Contrato/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: Contrato/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "fecha_Creacion,empresa_rut,fecha_Termino,,texto_contrato")]Contrato contrato)
        {
            try
            {
                // TODO: Add insert logic here
                if ( !ModelState.IsValid)
                {
                    
                    return View(contrato);
                }
                contrato.Save();
                TempData["mensaje"] = "Guardado Correctamente";
                return RedirectToAction("Index");
            }
            catch
            {
                return View(contrato);
            }
        }

        // GET: Contrato/Edit/5
        public ActionResult Edit(int id)
        {


            Contrato p = new Contrato().find(id);

            if (p == null)
            {
                TempData["mensaje"] = "El Contrato no existe";
                return RedirectToAction("Index");
            }
            return View(p);
        }

        // POST: Contrato/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "ID_Contrato,fecha_Creacion, empresa_rut, fecha_Termino,, texto_contrato")]Contrato contrato)
        {
            try
            {
                // TODO: Add update logic here
                contrato.Update();
                TempData["mensaje"] = "modificado correctamente";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Contrato/Delete/5
        public ActionResult Delete(int id)
        {

            if (new Contrato().find(id) == null)
            {
                TempData["mensaje"] = "no existe el producto";
                return RedirectToAction("Index");
            }

            if (new Contrato().Delete(id))
            {
                TempData["mensaje"] = "Eliminado Correctamente";
                return RedirectToAction("Index");
            }

            return View();
        }

        // POST: Contrato/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

NoMasAccidentes/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NoMasAccidentes.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

NoMasAccidentes/Views/Contrato/Create.cshtml
@model NoMasAccidentesNegocio.Contrato
@{
    ViewBag.Title = "Crear Contrato";
}

<h2>Agregar Nuevo Contrato</h2>
@Html.ValidationSummary()

@Html.ActionLink("listado de productos","index")
@using (Html.BeginForm())
{
    @Html.LabelFor(p => p.fecha_Creacion_Contrato)
    @Html.TextBoxFor(p => p.fecha_Creacion_Contrato)
    <br />
    @Html.LabelFor(p => p.empresa_Rut)
    @Html.TextBoxFor(p => p.empresa_Rut)
    <br />
    @Html.LabelFor(p => p.fecha_Termino_Contrato)
    @Html.TextBoxFor(p => p.fecha_Termino_Contrato)
    <br />
    @Html.LabelFor(p => p.texto_Contrato)
    @Html.TextBoxFor(p => p.texto_Contrato)
    <br />
    <button>Guardar</button>
}

NoMasAccidentes/Views/Contrato/Edit.cshtml
@model NoMasAccidentesNegocio.Contrato
@{
    ViewBag.Title = "Modificar Contrato";
}

<h2>Editar Datos del Contrato</h2>
@Html.ActionLink("Modificar Datos del Contrato", "index")
@using (Html.BeginForm())
{
    @Html.HiddenFor(p=>p.id_Contrato)
    @Html.LabelFor(p => p.fecha_Creacion_Contrato)
    @Html.TextBoxFor(p => p.fecha_Creacion_Contrato)
    <br />
    @Html.LabelFor(p => p.empresa_Rut)
    @Html.TextBoxFor(p => p.empresa_Rut)
    <br />
    @Html.LabelFor(p => p.fecha_Termino_Contrato)
    @Html.TextBoxFor(p => p.fecha_Termino_Contrato)
    <br />
    @Html.LabelFor(p => p.texto_Contrato)
    @Html.TextBoxFor(p => p.texto_Contrato)
    <br />
    <button>Modificar</button>
}

NoMasAccidentes/Views/Contrato/Index.cshtml
@using NoMasAccidentesNegocio


@{
    ViewBag.Title = "Index";
}

<h2>Listado de Contratos</h2>

@{List<Contrato> contratos = (List<Contrato>)ViewBag.contratos;}
@Html.ActionLink("Crear contrato", "Create")
<table>
        <tr>
            <th>id_contrato</th>
            <th>fecha_Creacion_Contrato</th>
            <th>empresa_Rut</th>
            <th>fecha_Termino_Contrato</th>
            <th>texto_Contrato</th>
            <th>Opciones</th>
        </tr>
            @foreach (var contrato in contratos)
            {
        <tr>
            <td>@contrato.id_Contrato</td>
            <td>@contrato.fecha_Creacion_Contrato</td>
            <td>@contrato.empresa_Rut</td>
            <td>@contrato.fecha_Termino_Contrato</td>
            <td>@contrato.texto_Contrato</td>
            <td>
                @Html.ActionLink("Eliminar", "Delete", new { id = contrato.id_Contrato })
                @Html.ActionLink("Modificar", "Edit", new { id = contrato.id_Contrato })

            </td>
        </tr>
            }

        
</table>

@TempData["mensaje"]

NoMasAccidentes/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Inicio</h2>
<p>Bienvenido a nuestro sistema No Mas Accidentes</p>

@Html.ActionLink("listado de productos", "index", "Contrato")

@Html.ActionLink("create contrato", "Create", "Contrato")

NoMasAccidentes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/layout.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="Titulo">
                    @Html.ActionLink("No Mas Accidentes", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
               
            </div>
            <div class="navbar-collapse collapse">
                
                    <ul class="nav navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li>
                                @Html.ActionLink("Cerrar Sesion", "LogOut", "Auth")
                            </li>
                            <li>
                                <div style="position: relative;display: block;padding: 15px 15px;color:white">@User.Identity.Name</div>

                            </li>
                        }
                        else
                        {
                            <li>
                                @Html.ActionLink("Iniciar Sesion", "Login", "Auth")
                            </li>
                        }

                    </ul>
             
                </div>
               
           
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>